#!/bin/bash
# A script to patch worker/src/index.js

# We will use awk to insert the new routes right before the "// 3. KV State Polling Endpoint" section

awk '
/^\s*\/\/ 3\. KV State Polling Endpoint/ {
    print "    // Generic CRUD Handler for KV Entities"
    print "    const kvRoutes = ["
    print "      { path: \"/api/data\", key: \"EXTRACTED_DATA\", default: [] },"
    print "      { path: \"/api/enrichment\", key: \"ENRICHMENT_LOGS\", default: [] },"
    print "      { path: \"/api/proxies\", key: \"PROXY_POOLS\", default: [] },"
    print "      { path: \"/api/settings\", key: \"NODE_SETTINGS\", default: {} }"
    print "    ];"
    print ""
    print "    const matchRoute = kvRoutes.find(r => url.pathname === r.path);"
    print "    if (matchRoute) {"
    print "      const authHeader = request.headers.get(\"Authorization\");"
    print "      if (authHeader !== `Bearer ${env.DASHBOARD_ACCESS_TOKEN}`) {"
    print "        return new Response(JSON.stringify({ error: \"Unauthorized Node Access\" }), {"
    print "          status: 401,"
    print "          headers: { \"Content-Type\": \"application/json\", \"Access-Control-Allow-Origin\": corsOrigin }"
    print "        });"
    print "      }"
    print ""
    print "      const kv = env.B2C_SCRAPER_STATE;"
    print "      if (!kv) {"
    print "         return new Response(JSON.stringify({ error: \"KV not configured\" }), { status: 500, headers: { \"Content-Type\": \"application/json\", \"Access-Control-Allow-Origin\": corsOrigin } });"
    print "      }"
    print ""
    print "      if (request.method === \"GET\") {"
    print "         let data = matchRoute.default;"
    print "         try {"
    print "             const dataStr = await kv.get(matchRoute.key);"
    print "             if (dataStr) data = JSON.parse(dataStr);"
    print "         } catch(e) { /* empty */ }"
    print "         return new Response(JSON.stringify(data), {"
    print "           status: 200,"
    print "           headers: { \"Content-Type\": \"application/json\", \"Access-Control-Allow-Origin\": corsOrigin }"
    print "         });"
    print "      }"
    print ""
    print "      if (request.method === \"POST\") {"
    print "         const payload = await request.json();"
    print "         let data = Array.isArray(matchRoute.default) ? [] : {};"
    print "         try {"
    print "             const dataStr = await kv.get(matchRoute.key);"
    print "             if (dataStr) data = JSON.parse(dataStr);"
    print "         } catch(e) { /* empty */ }"
    print ""
    print "         if (Array.isArray(data)) {"
    print "             payload.id = payload.id || crypto.randomUUID();"
    print "             payload.time = payload.time || new Date().toISOString();"
    print "             data.push(payload);"
    print "         } else {"
    print "             data = { ...data, ...payload };"
    print "         }"
    print ""
    print "         await kv.put(matchRoute.key, JSON.stringify(data));"
    print "         return new Response(JSON.stringify({ success: true, id: payload.id }), {"
    print "           status: 201,"
    print "           headers: { \"Content-Type\": \"application/json\", \"Access-Control-Allow-Origin\": corsOrigin }"
    print "         });"
    print "      }"
    print ""
    print "      if (request.method === \"PUT\") {"
    print "         const payload = await request.json();"
    print "         let data = Array.isArray(matchRoute.default) ? [] : {};"
    print "         try {"
    print "             const dataStr = await kv.get(matchRoute.key);"
    print "             if (dataStr) data = JSON.parse(dataStr);"
    print "         } catch(e) { /* empty */ }"
    print ""
    print "         if (Array.isArray(data)) {"
    print "             // PUT for array currently just acts as an append or update-by-id if needed,"
    print "             // assuming payload is a full object replacement for an item"
    print "             if (payload.id) {"
    print "                 const idx = data.findIndex(i => i.id === payload.id);"
    print "                 if (idx >= 0) data[idx] = { ...data[idx], ...payload };"
    print "                 else data.push(payload);"
    print "             }"
    print "         } else {"
    print "             // For objects, PUT will update key-value pairs"
    print "             if (payload.key) {"
    print "                 data[payload.key] = payload.value;"
    print "             } else {"
    print "                 data = { ...data, ...payload };"
    print "             }"
    print "         }"
    print ""
    print "         await kv.put(matchRoute.key, JSON.stringify(data));"
    print "         return new Response(JSON.stringify({ success: true }), {"
    print "           status: 200,"
    print "           headers: { \"Content-Type\": \"application/json\", \"Access-Control-Allow-Origin\": corsOrigin }"
    print "         });"
    print "      }"
    print ""
    print "      if (request.method === \"DELETE\") {"
    print "         // Basic delete, clears all or specific if handled"
    print "         await kv.delete(matchRoute.key);"
    print "         return new Response(JSON.stringify({ success: true }), {"
    print "           status: 200,"
    print "           headers: { \"Content-Type\": \"application/json\", \"Access-Control-Allow-Origin\": corsOrigin }"
    print "         });"
    print "      }"
    print "    }"
    print ""
}
{ print }
' worker/src/index.js > worker/src/index.js.tmp && mv worker/src/index.js.tmp worker/src/index.js
